### ISSUE TITLE
Platform specific split string?

### ISSUE THREAD

**Issue by jeroen** [lebebr01/pdfsearch#10]
If I run the example from the readme I see different output:

<img width="936" alt="screen shot 2018-04-09 at 7 45 11 pm" src="https://user-images.githubusercontent.com/216319/38513483-a9744cbe-3c2e-11e8-8ff3-b0af9a6623b7.png">

Is this expected? I noticed [you split by `\r\n`](https://github.com/lebebr01/pdfsearch/blob/master/R/split_pdf.r#L3) which is windows-specific I think? Did you test the package on non-windows machines?

**Comment by lebebr01** [comment]
This is not expected and not an issue I was aware of. I do not have a non-windows machine currently to run some local tests like this on. 

When I wrote this portion of the code I was not aware of the tokenizers package. It would likely be more robust to use their `tokenize_lines` function to perform this action. 

I will also brainstorm a unit test that would catch this behavior as well. I'm open to ideas for a good way to test this.

**Comment by jeroen** [comment]
Yes you should add a unit test for this. You can automatically run checks on linux and osx using travis.

**Comment by lebebr01** [comment]
e8d8e90c63a9730cd0e99ea8defe7ea5c5bc705a should fix issue. 

Added unit test here to test for literal "\n" characters in result text: [test here](https://github.com/lebebr01/pdfsearch/blob/e8d8e90c63a9730cd0e99ea8defe7ea5c5bc705a/tests/testthat/test_structure.r#L81-L90). Open to other ways to test this behavior.

**Comment by jeroen** [comment]
OK thanks. BTW you could reduce your dependency weight by calling `stringi::stri_split_lines()` and `stringi::stri_split_boundaries(x, type = "word")` directly rather than via tokenizers.
