### ISSUE TITLE
Change depends to imports

### ISSUE THREAD

**Issue by lmullen** [lebebr01/pdfsearch#12]
Issue from [JOSS review](https://github.com/openjournals/joss-reviews/issues/668)

The package currently uses `Depends` in the `DESCRIPTION` for its dependencies. Best practice is to use `Imports`, and then to refer to the function by its namespace: e.g., `somepackage::some_func()`. See Hadley Wickham's [R Packages](http://r-pkgs.had.co.nz/description.html).

**Comment by lebebr01** [comment]
Made this change. I was not aware of the `Imports` section, however have been using the `package::func()` syntax.
