### ISSUE TITLE
Corrections to vignette

### ISSUE THREAD

**Issue by lmullen** [lebebr01/pdfsearch#13]
Issue for [JOSS review](https://github.com/openjournals/joss-reviews/issues/668).

- [x] Please give the vignette a title.
- [x] It would also be good to rename the vignette file to something less generic, like `intro-to-pdfsearch` or so on.

See this image for what the vignette currently shows up as:

<img width="482" alt="screenshot 2018-05-08 14 02 16" src="https://user-images.githubusercontent.com/183672/39774356-9cd67684-52c8-11e8-80ae-8900668673f4.png">

**Comment by lebebr01** [comment]
Added the title, "Getting Started with pdfsearch" to the \VignetteIndexEntry command. 

I also made the suggested change to the vignette filename. The filename is now `intro_to_pdfsearch.Rmd`. I stuck with underscores as this is what I tend to use for all filenames in the package.
