### ISSUE TITLE
PDF error: FoFiType1::parse a line has more than 255 characters, we don't support this

### ISSUE THREAD

**Issue by ghost** [lebebr01/pdfsearch#28]
I got this message when executing keyword_directory() and  keyword_search().

**Comment by lebebr01** [comment]
Thanks for submitting this. This seems to be an issue with the underlying poppler library. For example see, https://gitlab.com/pdfgrep/pdfgrep/-/issues/18. 

I'm going to close this as it isn't an issue with the package, but with the underlying dependency that reads in the PDF document.
